### ISSUE TITLE
want tests for Unicorn application server

### ISSUE THREAD

**Issue by bixu** [bixu/lx_kitchen#5]
See https://github.com/joyent/illumos-joyent/issues/48

@sax, any ideas about how to best test this?

**Comment by bbhoss** [comment]
I can't figure out how to make this BATS stuff work with daemons, and I don't have any more time to dedicate to this right now. Here's what I've got so far

``` bash
setup() {
  apt-get install -y unicorn
  curl https://gist.githubusercontent.com/bbhoss/501436de9a8bd2f835b7/raw/6689933ad3c1aaddb5b2368685a8c36d9c1ffdbc/gistfile1.rb > /tmp/example.ru
}

@test "unicorn boots and serves rack app" {
  pkill -f unicorn
  unicorn -D -l127.0.0.1:8080 /tmp/example.ru
  run curl http://localhost:8080
  [ "$status" -eq 0 ]
}
```

You'll see if you run unicorn without the -D, it will give the EINVAL error immediately.

```
root@672516b2-ae00-4fde-8458-e4403e87a60f:/tmp/busser# unicorn -l127.0.0.1:8080 /tmp/example.ru
E, [2015-04-10T17:52:17.331548 #35713] ERROR -- : 127.0.0.1:8080 {:tcp_defer_accept=>1, :accept_filter=>"httpready", :backlog=>1024, :tcp_nopush=>nil, :tcp_nodelay=>true}: Protocol not available (Errno::ENOPROTOOPT)
E, [2015-04-10T17:52:17.332296 #35713] ERROR -- : /usr/lib/ruby/vendor_ruby/unicorn/socket_helper.rb:99:in `setsockopt'
E, [2015-04-10T17:52:17.332457 #35713] ERROR -- : /usr/lib/ruby/vendor_ruby/unicorn/socket_helper.rb:99:in `set_tcp_sockopt'
E, [2015-04-10T17:52:17.332693 #35713] ERROR -- : /usr/lib/ruby/vendor_ruby/unicorn/socket_helper.rb:115:in `set_server_sockopt'
E, [2015-04-10T17:52:17.332957 #35713] ERROR -- : /usr/lib/ruby/vendor_ruby/unicorn/socket_helper.rb:169:in `bind_listen'
E, [2015-04-10T17:52:17.333195 #35713] ERROR -- : /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:255:in `listen'
E, [2015-04-10T17:52:17.333389 #35713] ERROR -- : /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:801:in `block in bind_new_listeners!'
E, [2015-04-10T17:52:17.333616 #35713] ERROR -- : /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:801:in `each'
E, [2015-04-10T17:52:17.333877 #35713] ERROR -- : /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:801:in `bind_new_listeners!'
E, [2015-04-10T17:52:17.334112 #35713] ERROR -- : /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:146:in `start'
E, [2015-04-10T17:52:17.334342 #35713] ERROR -- : /usr/bin/unicorn:126:in `<main>'
I, [2015-04-10T17:52:17.334508 #35713]  INFO -- : listening on addr=127.0.0.1:8080 fd=7
I, [2015-04-10T17:52:17.334794 #35713]  INFO -- : worker=0 spawning...
I, [2015-04-10T17:52:17.406138 #35715]  INFO -- : worker=0 spawned pid=35715
I, [2015-04-10T17:52:17.406797 #35715]  INFO -- : Refreshing Gem list
I, [2015-04-10T17:52:17.416188 #35713]  INFO -- : master process ready
I, [2015-04-10T17:52:17.450328 #35715]  INFO -- : worker=0 ready
E, [2015-04-10T17:52:17.450964 #35715] ERROR -- : listen loop error: Invalid argument - accept (Errno::EINVAL)
E, [2015-04-10T17:52:17.452204 #35715] ERROR -- : /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:659:in `kgio_tryaccept'
E, [2015-04-10T17:52:17.452409 #35715] ERROR -- : /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:659:in `worker_loop'
E, [2015-04-10T17:52:17.452664 #35715] ERROR -- : /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:527:in `spawn_missing_workers'
E, [2015-04-10T17:52:17.452975 #35715] ERROR -- : /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:153:in `start'
E, [2015-04-10T17:52:17.453248 #35715] ERROR -- : /usr/bin/unicorn:126:in `<main>'
```
